# Load Dataset

In [49]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
# dataset=pd.read_excel("/Users/empty/PycharmProjects/ML-CW-2/Data/trainDataset.xls")
dataset=pd.read_excel("C:/Users/10253/Desktop/ML-CW-2/Data/trainDataset.xls")
dataset=dataset[dataset["pCR (outcome)"]!=999]
dataset.head(len(dataset))

ID  pCR (outcome)  RelapseFreeSurvival (outcome)   Age  ER  PgR  \
0    TRG002174              1                     144.000000  41.0   0    0   
1    TRG002178              0                     142.000000  39.0   1    1   
2    TRG002204              1                     135.000000  31.0   0    0   
3    TRG002206              0                      12.000000  35.0   0    0   
4    TRG002210              0                     109.000000  61.0   1    0   
..         ...            ...                            ...   ...  ..  ...   
395  TRG002955              1                      49.250000  46.1   0    0   
396  TRG002958              0                      48.500000  53.3   0    0   
397  TRG002961              0                      47.500000  68.8   1    0   
398  TRG002962              0                      46.916667  46.0   1    0   
399  TRG002963              1                      46.750000  55.3   0    0   

     HER2  TrippleNegative  ChemoGrade  Proliferation  ...  \
0       0                1           3              3  ...   
1       0                0           3              3  ...   
2       0                1           2              1  ...   
3       0                1           3              3  ...   
4       0                0           2              1  ...   
..    ...              ...         ...            ...  ...   
395     0                1           3              3  ...   
396     0                1           2              1  ...   
397     0                0           3              3  ...   
398     0                0           2              1  ...   
399     1                0           2              1  ...   

     original_glszm_SmallAreaHighGrayLevelEmphasis  \
0                                         0.517172   
1                                         0.444391   
2                                         0.534549   
3                                         0.506185   
4                                         0.462282   
..                                             ...   
395                                       0.439568   
396                                       0.527779   
397                                       0.313693   
398                                       0.670229   
399                                       0.552491   

     original_glszm_SmallAreaLowGrayLevelEmphasis  original_glszm_ZoneEntropy  \
0                                        0.375126                    3.325332   
1                                        0.444391                    3.032144   
2                                        0.534549                    2.485848   
3                                        0.506185                    2.606255   
4                                        0.462282                    2.809279   
..                                            ...                         ...   
395                                      0.439568                    3.056046   
396                                      0.527778                    1.500000   
397                                      0.313693                    3.573557   
398                                      0.670229                    1.857045   
399                                      0.552491                    2.671677   

     original_glszm_ZonePercentage  original_glszm_ZoneVariance  \
0                         0.002314                 3.880772e+06   
1                         0.005612                 2.372010e+06   
2                         0.006752                 1.540027e+06   
3                         0.003755                 6.936741e+06   
4                         0.006521                 1.265399e+06   
..                             ...                          ...   
395                       0.001339                 1.671271e+07   
396                       0.003728                 2.132007e+05   
397                       0.001112                 2.008034e+07   
398                       

In [50]:
# from sklearn.impute import  SimpleImputer
# imp=SimpleImputer(missing_values=np.nan,strategy='mean')
# names=dataset.columns.drop('ID')
# a=imp.fit_transform(dataset.drop('ID',axis=1))
# imp=SimpleImputer(missing_values=999,strategy='mean')
# a=imp.fit_transform(a)
# df=pd.DataFrame(a,columns=
#                 names)
# df

# Data Preprocessing

### Removing duplicate

In [51]:
dataset.drop_duplicates(inplace=True) #because with 119 features, it is unlikely that exact same data happens in real world, it is useless for training and testing; hence remove it before dataset split

### Split Dataset

In [52]:
dataset['pCR (outcome)'].value_counts()

0    299
1     96
Name: pCR (outcome), dtype: int64

In [53]:
y=dataset['pCR (outcome)']
X=dataset.drop(['pCR (outcome)','RelapseFreeSurvival (outcome)'],axis=1)
X=dataset[['Age','ER','PgR','HER2','TrippleNegative','ChemoGrade','Proliferation','HistologyType','LNStatus','TumourStage']]
global_seed=2
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=global_seed)

### drop columns that are not applicable

In [54]:
class columnDropperTransformer(): #https://stackoverflow.com/questions/68402691/adding-dropping-column-instance-into-a-pipeline
    def __init__(self,columns):
        self.columns=columns

    def fit(self,X,y=None):
        return self

    def transform(self,X,y=None):
        return X.drop(self.columns,axis=1)

    def fit_transform(self,X,y=None):
        return X.drop(self.columns,axis=1)

# dropper = columnDropperTransformer(['ID'])
# X_train=dropper.fit_transform(X_train)
#
# X_test=dropper.transform(X_test)

### missing data

In [55]:
dataset.isnull().sum()

ID                               0
pCR (outcome)                    0
RelapseFreeSurvival (outcome)    0
Age                              0
ER                               0
                                ..
original_ngtdm_Busyness          0
original_ngtdm_Coarseness        0
original_ngtdm_Complexity        0
original_ngtdm_Contrast          0
original_ngtdm_Strength          0
Length: 120, dtype: int64

In [56]:
from sklearn.impute import KNNImputer

names=X_train.columns

imp=KNNImputer(missing_values=np.nan,n_neighbors=200)
# X_train[:]=imp.fit_transform(X_train)
# X_test[:]=imp.transform(X_test)
X_train=imp.fit_transform(X_train)
X_test=imp.transform(X_test)

imp.missing_values=np.float64(999)
# X_train[:]=imp.fit_transform(X_train)
# X_test[:]=imp.transform(X_test)
X_train=imp.fit_transform(X_train)
X_test=imp.transform(X_test)

### Removing outliers

In [57]:
from sklearn.neighbors import LocalOutlierFactor

# because use LocalOutlierFactor may lose useful information becuase whenever there is an outlier in any features of the sample, the sample will be detected as outlier sample and all its information will be set to 999
# therefore, use other method

class outlierHandlingWithDev():
    def fit(self,X,y=None):
        self.mean=np.zeros(len(X[0]))
        self.std=np.zeros(len(X[0]))
        for i in range(len(X[0])):
            self.mean[i]=X[:,i].mean()
            self.std[i]=X[:,i].std()

        return self

    def transform(self,X,y=None):
        for i in range(len(X)):
            for j in range(len(X[i])):
                if np.abs(X[i][j]-self.mean[j])>3*self.std[j]:
                    X[i][j]=999
        return X

    def fit_transform(self,X,y=None):
        self.fit(X,y)
        return self.transform(X,y)
    # def fit(self,X,y=None):
    #     self.mean=X.mean(axis=0)
    #     self.std=X.std(axis=0)
    #
    #     return self
    #
    # def transform(self,X,y=None):
    #     for i in X.columns:
    #         for j in range(len(X)):
    #             if abs(X[i][j]-self.mean[i])>(3*self.std[i]):
    #                 X[i][j]=999
    #
    #     return X
    #
    # def fit_transform(self,X,y=None):
    #     self.fit(X,y)
    #     return self.transform(X,y)

# detector=outlierHandlingWithDev()
# detector.fit(X_train)
# detector.transform(X_train)
# detector.transform(X_test)
#
# X_train=imp.fit_transform(X_train)
# X_test=imp.transform(X_test)

X_train=pd.DataFrame(X_train,columns=names)
X_test=pd.DataFrame(X_test,columns=names)

### Binning

In [58]:
# from sklearn.preprocessing import Binarizer
# datasetCopy=dataset.iloc[:,3].values.reshape(-1,1)
# transformor=Binarizer(threshold=40).fit(datasetCopy)
# transformor
# x1=transformor.transform(datasetCopy)
# dataset.iloc[:,3]=x1
# dataset

In [59]:
# datasetCopy=dataset.iloc[:,3].values.reshape(-1,1)
# transformor=Binarizer(threshold=40).fit(datasetCopy)
# transformor
# x1=transformor.transform(datasetCopy)
# dataset.iloc[:,3]=x1
# dataset

In [60]:
from sklearn.preprocessing import KBinsDiscretizer
datasetCopy=dataset.iloc[:,3].values.reshape(-1,1)
# 不能导入一维，所以reshape
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')
est.fit(datasetCopy)
Xt = est.transform(datasetCopy)
set(Xt.ravel())
dataset.iloc[:,3]=Xt
dataset

ID  pCR (outcome)  RelapseFreeSurvival (outcome)  Age  ER  PgR  \
0    TRG002174              1                     144.000000  0.0   0    0   
1    TRG002178              0                     142.000000  0.0   1    1   
2    TRG002204              1                     135.000000  0.0   0    0   
3    TRG002206              0                      12.000000  0.0   0    0   
4    TRG002210              0                     109.000000  2.0   1    0   
..         ...            ...                            ...  ...  ..  ...   
395  TRG002955              1                      49.250000  0.0   0    0   
396  TRG002958              0                      48.500000  1.0   0    0   
397  TRG002961              0                      47.500000  2.0   1    0   
398  TRG002962              0                      46.916667  0.0   1    0   
399  TRG002963              1                      46.750000  1.0   0    0   

     HER2  TrippleNegative  ChemoGrade  Proliferation  ...  \
0       0                1           3              3  ...   
1       0                0           3              3  ...   
2       0                1           2              1  ...   
3       0                1           3              3  ...   
4       0                0           2              1  ...   
..    ...              ...         ...            ...  ...   
395     0                1           3              3  ...   
396     0                1           2              1  ...   
397     0                0           3              3  ...   
398     0                0           2              1  ...   
399     1                0           2              1  ...   

     original_glszm_SmallAreaHighGrayLevelEmphasis  \
0                                         0.517172   
1                                         0.444391   
2                                         0.534549   
3                                         0.506185   
4                                         0.462282   
..                                             ...   
395                                       0.439568   
396                                       0.527779   
397                                       0.313693   
398                                       0.670229   
399                                       0.552491   

     original_glszm_SmallAreaLowGrayLevelEmphasis  original_glszm_ZoneEntropy  \
0                                        0.375126                    3.325332   
1                                        0.444391                    3.032144   
2                                        0.534549                    2.485848   
3                                        0.506185                    2.606255   
4                                        0.462282                    2.809279   
..                                            ...                         ...   
395                                      0.439568                    3.056046   
396                                      0.527778                    1.500000   
397                                      0.313693                    3.573557   
398                                      0.670229                    1.857045   
399                                      0.552491                    2.671677   

     original_glszm_ZonePercentage  original_glszm_ZoneVariance  \
0                         0.002314                 3.880772e+06   
1                         0.005612                 2.372010e+06   
2                         0.006752                 1.540027e+06   
3                         0.003755                 6.936741e+06   
4                         0.006521                 1.265399e+06   
..                             ...                          ...   
395                       0.001339                 1.671271e+07   
396                       0.003728                 2.132007e+05   
397                       0.001112                 2.008034e+07   
398                       0.006706    

### MinMaxScaler

In [61]:
# from sklearn.preprocessing import MinMaxScaler
# scaler=MinMaxScaler()
# X_train[:]=scaler.fit_transform(X_train)
# X_test[:]=scaler.transform(X_test)
# X_train
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[:]=scaler.fit_transform(X_train)
X_test[:]=scaler.transform(X_test)


### PCA

In [62]:
corr=X_train.corr()
corr=corr.where(abs(corr)>0.9)
count = 0
corr_fea = []

for i in corr.columns:
    for j in corr.columns:
        if abs(corr[i][j])>0.9 and i!=j:
            if i not in corr_fea:
                count+=1
                corr_fea.append(i)

            if j not in corr_fea:
                count+=1
                corr_fea.append(j)

count

0

In [63]:
def is_related(pair1, pair2):
    if (pair1[0] in pair2 or pair1[1] in pair2) and pair1!=pair2 and not (pair1[0]==pair2[1] and pair1[1]==pair2[0]):
        return True
    return False

def add_relation(corr_fea):
    for i in range(len(corr_fea)):
        for j in range(i,len(corr_fea)):
            if i!=j:
                if is_related(corr_fea[i],corr_fea[j]):
                    fea1=tuple(set(corr_fea[i])-set(corr_fea[j]))
                    fea2=tuple(set(corr_fea[j])-set(corr_fea[i]))
                    fea=fea1+fea2
                    if fea not in corr_fea and rev(fea) not in corr_fea:
                        corr_fea.append((fea1+fea2))

def rev(fea):
    f1=fea[0]
    f2=fea[1]

    return (f2,f1)

corr=X_train.corr()
corr=corr.where(abs(corr)>0.9)
count=0
corr_fea=[]
for i in corr.columns:
    for j in corr.columns:
        if i!=j and abs(corr[i][j])>0.9 and ((i,j) not in corr_fea) and ((j,i) not in corr_fea):
            count+=1
            corr_fea.append((i,j))
            add_relation(corr_fea)


In [64]:
from sklearn.decomposition import PCA

new_num_fea=len(X_train.columns)-count

pca=PCA(n_components=new_num_fea)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)


### Feature Selection

### resample

In [65]:
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek

smote=SMOTETomek()

X_train,y_train=smote.fit_resample(X_train,y=y_train)


# Methods

In [66]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV, KFold, cross_val_score
from sklearn.feature_selection import SequentialFeatureSelector

clf=MLPClassifier(hidden_layer_sizes=(20,30),activation="relu",alpha=0.04,max_iter=1000,batch_size=20,random_state=global_seed,early_stopping=True,shuffle=True)
score=cross_val_score(clf,X_train,y_train,cv=KFold(n_splits=5,shuffle=True,random_state=global_seed))
print(score.mean())

clf.fit(X_train,y_train)
print(classification_report(y_test,clf.predict(X_test)))
confusion_matrix(y_test,clf.predict(X_test))
# confusion_matrix(y_train,clf.predict(X_train))
# seq.fit(X_train,y_train)
# X_train=seq.transform(X_train)
# X_test=seq.transform(X_test)
# clf.fit(X_train,y_train)
# print(classification_report(y_test,clf.predict(X_test)))
# confusion_matrix(y_test,clf.predict(X_test))

0.6695863125638406
              precision    recall  f1-score   support

           0       0.88      0.58      0.70        60
           1       0.36      0.74      0.48        19

    accuracy                           0.62        79
   macro avg       0.62      0.66      0.59        79
weighted avg       0.75      0.62      0.65        79



array([[35, 25],
       [ 5, 14]], dtype=int64)

In [67]:
# from sklearn.metrics import confusion_matrix
# from sklearn.tree import  DecisionTreeClassifier
# from sklearn.metrics import classification_report
# from sklearn.feature_selection import SequentialFeatureSelector
# clf=DecisionTreeClassifier(class_weight='balanced',random_state=global_seed)
# # clf.fit(X_train,y_train)
# # clf.predict(X_test)
#
# clf.fit(X_train,y_train)
#
# print(classification_report(y_test,clf.predict(X_test)))
# confusion_matrix(y_test,clf.predict(X_test))

In [72]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(hidden_layer_sizes=(23,30),alpha=0.1,activation="relu",max_iter=500,batch_size=20)
# cross_val_score(clf,X_train,y_train,cv=3)
from sklearn.feature_selection import SequentialFeatureSelector
# sfs=SequentialFeatureSelector(clf,n_features_to_select="auto")
#
clf.fit(X_train,y_train)
print(classification_report(y_test,clf.predict(X_test)))
confusion_matrix(y_test,clf.predict(X_test))
confusion_matrix(y_train,clf.predict(X_train))

              precision    recall  f1-score   support

           0       0.77      0.80      0.79        60
           1       0.29      0.26      0.28        19

    accuracy                           0.67        79
   macro avg       0.53      0.53      0.53        79
weighted avg       0.66      0.67      0.66        79



array([[218,   3],
       [  6, 215]], dtype=int64)

In [69]:
from sklearn.svm import SVC
clf=SVC(kernel="poly",random_state=global_seed,degree=2)
para={'kernel':["poly","linear","rbf"],'degree':[1,2,3,4,5],'class_weight':[{0:1.,1:2.},{0:1.,1:20.},None]}
cv=GridSearchCV(clf,param_grid=para,cv=KFold(n_splits=5,random_state=global_seed,shuffle=True))
cv.fit(X_train,y_train)
print(cv.best_params_)
print(confusion_matrix(cv.predict(X_test),y_test))
print(classification_report(cv.predict(X_test),y_test))

# clf.fit(X_train,y_train)
confusion_matrix(y_true=y_train,y_pred=cv.predict(X_train))

{'class_weight': {0: 1.0, 1: 2.0}, 'degree': 5, 'kernel': 'poly'}
[[36  9]
 [24 10]]
              precision    recall  f1-score   support

           0       0.60      0.80      0.69        45
           1       0.53      0.29      0.38        34

    accuracy                           0.58        79
   macro avg       0.56      0.55      0.53        79
weighted avg       0.57      0.58      0.55        79



array([[164,  57],
       [  8, 213]], dtype=int64)

In [70]:
from sklearn.neighbors import KNeighborsClassifier

clf=KNeighborsClassifier(weights="distance")
para={'n_neighbors':[2,3,4,5,6,7,8,9,10,12,15,19]}
cv=GridSearchCV(clf,param_grid=para,cv=KFold(n_splits=5,random_state=global_seed,shuffle=True))
cv.fit(X_train,y_train)
print(confusion_matrix(cv.predict(X_test),y_test))

# cv.estimator.fit(X_train,y_train)
# confusion_matrix(y_true=y_test,y_pred=clf.predict(X_test))
print(classification_report(y_test,cv.predict(X_test)))

[[49 13]
 [11  6]]
              precision    recall  f1-score   support

           0       0.79      0.82      0.80        60
           1       0.35      0.32      0.33        19

    accuracy                           0.70        79
   macro avg       0.57      0.57      0.57        79
weighted avg       0.69      0.70      0.69        79



In [71]:
# from sklearn.utils import class_weight
# import tensorflow as tf
# from tensorflow import keras
# model=keras.Sequential()
# model.add(keras.layers.Dense(20,input_dim=len(X_train[0]),activation="relu"))
# model.add(keras.layers.Dense(10,activation="relu"))
# model.add(keras.layers.Dense(1,activation="sigmoid"))
# model.summary()
#
# model.compile(loss="binary_crossentropy",optimizer="adam",metrics=[tf.keras.metrics.Precision(),"accuracy"])
# # model.save_weights('model.h5')
# # model.load_weights('model.h5')
# history=model.fit(X_train,np.array(y_train),epochs=20,validation_data=(X_test,np.array(y_test)),batch_size=20)
# y_pred=model.predict(X_test)
# loss,precision,acc=model.evaluate(X_test,np.array(y_test),verbose=2)

