# Load Dataset

In [99]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

dataset=pd.read_excel("C:/Users/10253/Desktop/ML-CW-2/Data/trainDataset.xls")
dataset=dataset[dataset["pCR (outcome)"]!=999]
dataset.head(len(dataset))

ID  pCR (outcome)  RelapseFreeSurvival (outcome)   Age  ER  PgR  \
0    TRG002174              1                     144.000000  41.0   0  0.0   
1    TRG002178              0                     142.000000  39.0   1  1.0   
2    TRG002204              1                     135.000000  31.0   0  0.0   
3    TRG002206              0                      12.000000  35.0   0  0.0   
4    TRG002210              0                     109.000000  61.0   1  0.0   
..         ...            ...                            ...   ...  ..  ...   
395  TRG002955              1                      49.250000  46.1   0  0.0   
396  TRG002958              0                      48.500000  53.3   0  0.0   
397  TRG002961              0                      47.500000  68.8   1  0.0   
398  TRG002962              0                      46.916667  46.0   1  0.0   
399  TRG002963              1                      46.750000  55.3   0  0.0   

     HER2  TrippleNegative  ChemoGrade  Proliferation  ...  \
0     0.0              1.0           3              3  ...   
1     0.0              0.0           3              3  ...   
2     0.0              1.0           2              1  ...   
3     0.0              1.0           3              3  ...   
4     0.0              0.0           2              1  ...   
..    ...              ...         ...            ...  ...   
395   0.0              1.0           3              3  ...   
396   0.0              1.0           2              1  ...   
397   0.0              0.0           3              3  ...   
398   0.0              0.0           2              1  ...   
399   1.0              0.0           2              1  ...   

     original_glszm_SmallAreaHighGrayLevelEmphasis  \
0                                         0.517172   
1                                         0.444391   
2                                         0.534549   
3                                         0.506185   
4                                         0.462282   
..                                             ...   
395                                       0.439568   
396                                       0.527779   
397                                       0.313693   
398                                       0.670229   
399                                       0.552491   

     original_glszm_SmallAreaLowGrayLevelEmphasis  original_glszm_ZoneEntropy  \
0                                        0.375126                    3.325332   
1                                        0.444391                    3.032144   
2                                        0.534549                    2.485848   
3                                        0.506185                    2.606255   
4                                        0.462282                    2.809279   
..                                            ...                         ...   
395                                      0.439568                    3.056046   
396                                      0.527778                    1.500000   
397                                      0.313693                    3.573557   
398                                      0.670229                    1.857045   
399                                      0.552491                    2.671677   

     original_glszm_ZonePercentage  original_glszm_ZoneVariance  \
0                         0.002314                 3.880772e+06   
1                         0.005612                 2.372010e+06   
2                         0.006752                 1.540027e+06   
3                         0.003755                 6.936741e+06   
4                         0.006521                 1.265399e+06   
..                             ...                          ...   
395                       0.001339                 1.671271e+07   
396                       0.003728                 2.132007e+05   
397                       0.001112                 2.008034e+07   
398                       

In [100]:
# from sklearn.impute import  SimpleImputer
# imp=SimpleImputer(missing_values=np.nan,strategy='mean')
# names=dataset.columns.drop('ID')
# a=imp.fit_transform(dataset.drop('ID',axis=1))
# imp=SimpleImputer(missing_values=999,strategy='mean')
# a=imp.fit_transform(a)
# df=pd.DataFrame(a,columns=
#                 names)
# df

# Data Preprocessing

### Removing duplicate

In [101]:
dataset.drop_duplicates(inplace=True) #because with 119 features, it is unlikely that exact same data happens in real world, it is useless for training and testing; hence remove it before dataset split

### Split Dataset

In [102]:
dataset['pCR (outcome)'].value_counts()

0    299
1     96
Name: pCR (outcome), dtype: int64

In [103]:
y=dataset['pCR (outcome)']
X=dataset.drop(['pCR (outcome)'],axis=1)


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=1)

### drop columns that are not applicable

In [104]:
class columnDropperTransformer(): #https://stackoverflow.com/questions/68402691/adding-dropping-column-instance-into-a-pipeline
    def __init__(self,columns):
        self.columns=columns

    def fit(self,X,y=None):
        return self

    def transform(self,X,y=None):
        return X.drop(self.columns,axis=1)

    def fit_transform(self,X,y=None):
        return X.drop(self.columns,axis=1)

dropper = columnDropperTransformer(['ID'])
X_train=dropper.fit_transform(X_train)

X_test=dropper.transform(X_test)

### missing data

In [105]:
dataset.isnull().sum()

ID                               0
pCR (outcome)                    0
RelapseFreeSurvival (outcome)    0
Age                              0
ER                               0
                                ..
original_ngtdm_Busyness          0
original_ngtdm_Coarseness        0
original_ngtdm_Complexity        0
original_ngtdm_Contrast          0
original_ngtdm_Strength          0
Length: 120, dtype: int64

In [106]:
from sklearn.impute import KNNImputer

names=X_train.columns

imp=KNNImputer(missing_values=np.nan,n_neighbors=10)
# X_train[:]=imp.fit_transform(X_train)
# X_test[:]=imp.transform(X_test)
X_train=imp.fit_transform(X_train)
X_test=imp.transform(X_test)

imp.missing_values=np.float64(999)
# X_train[:]=imp.fit_transform(X_train)
# X_test[:]=imp.transform(X_test)
X_train=imp.fit_transform(X_train)
X_test=imp.transform(X_test)

### Removing outliers

In [107]:
from sklearn.neighbors import LocalOutlierFactor

# because use LocalOutlierFactor may lose useful information becuase whenever there is an outlier in any features of the sample, the sample will be detected as outlier sample and all its information will be set to 999
# therefore, use other method

class outlierHandlingWithDev():
    def fit(self,X,y=None):
        self.mean=np.zeros(len(X[0]))
        self.std=np.zeros(len(X[0]))
        for i in range(len(X[0])):
            self.mean[i]=X[:,i].mean()
            self.std[i]=X[:,i].std()

        return self

    def transform(self,X,y=None):
        for i in range(len(X)):
            for j in range(len(X[i])):
                if np.abs(X[i][j]-self.mean[j])>3*self.std[j]:
                    X[i][j]=999
        return X

    def fit_transform(self,X,y=None):
        self.fit(X,y)
        return self.transform(X,y)
    # def fit(self,X,y=None):
    #     self.mean=X.mean(axis=0)
    #     self.std=X.std(axis=0)
    #
    #     return self
    #
    # def transform(self,X,y=None):
    #     for i in X.columns:
    #         for j in range(len(X)):
    #             if abs(X[i][j]-self.mean[i])>(3*self.std[i]):
    #                 X[i][j]=999
    #
    #     return X
    #
    # def fit_transform(self,X,y=None):
    #     self.fit(X,y)
    #     return self.transform(X,y)

detector=outlierHandlingWithDev()
detector.fit(X_train)
detector.transform(X_train)
detector.transform(X_test)

X_train=imp.fit_transform(X_train)
X_test=imp.transform(X_test)

X_train=pd.DataFrame(X_train,columns=names)
X_test=pd.DataFrame(X_test,columns=names)

### Binning

### resample

In [108]:
from imblearn.over_sampling import SMOTE

smote=SMOTE()

X_train,y_train=smote.fit_resample(X_train,y_train)


### MinMaxScaler

In [109]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train[:]=scaler.fit_transform(X_train)
X_test[:]=scaler.transform(X_test)
X_train

RelapseFreeSurvival (outcome)       Age        ER       PgR      HER2  \
0                         0.370690  0.542087  0.000000  0.000000  0.000000   
1                         0.741379  0.247337  0.000000  0.000000  0.000000   
2                         0.767241  0.777344  1.000000  0.000000  1.000000   
3                         0.129310  0.459340  0.000000  0.000000  0.000000   
4                         0.387931  0.516790  1.000000  1.000000  0.000000   
..                             ...       ...       ...       ...       ...   
473                       0.409828  0.591029  0.000000  0.000000  0.400185   
474                       0.291917  0.490428  0.030038  0.030038  0.030038   
475                       0.378168  0.773216  0.000000  0.000000  0.000000   
476                       0.381968  0.466615  0.198520  0.198520  0.198520   
477                       0.606204  0.454662  0.995948  0.995948  0.995948   

     TrippleNegative  ChemoGrade  Proliferation  HistologyType  LNStatus  ...  \
0           1.000000    0.500000       0.000000            0.0  0.000000  ...   
1           1.000000    1.000000       1.000000            0.0  0.000000  ...   
2           0.000000    0.500000       0.000000            0.0  0.000000  ...   
3           1.000000    0.500000       0.000000            0.0  1.000000  ...   
4           0.000000    0.500000       0.000000            0.0  1.000000  ...   
..               ...         ...            ...            ...       ...  ...   
473         0.599815    1.000000       0.700093            0.0  0.400185  ...   
474         0.969962    0.515019       0.030038            0.0  1.000000  ...   
475         1.000000    1.000000       0.500000            0.0  0.905624  ...   
476         0.801480    0.599260       0.198520            0.0  1.000000  ...   
477         0.004052    0.502026       0.004052            0.0  0.000000  ...   

     original_glszm_SmallAreaHighGrayLevelEmphasis  \
0                                         0.455968   
1                                         0.432894   
2                                         0.389308   
3                                         0.546080   
4                                         0.337877   
..                                             ...   
473                                       0.433183   
474                                       0.592461   
475                                       0.101955   
476                                       0.494050   
477                                       0.578543   

     original_glszm_SmallAreaLowGrayLevelEmphasis  original_glszm_ZoneEntropy  \
0                                        0.460253                    0.638994   
1                                        0.436964                    0.546212   
2                                        0.392968                    0.563218   
3                                        0.551214                    0.513451   
4                                        0.341053                    0.757515   
..                                            ...                         ...   
473                                      0.437255                    0.485163   
474                                      0.598030                    0.224649   
475                                      0.102913                    0.458954   
476                                      0.498695                    0.315029   
477                                      0.583980                    0.275804   

     original_glszm_ZonePercentage  original_glszm_ZoneVariance  \
0                         0.587399                     0.003439   
1                         0.127545                     0.020124   
2                         0.022627                     0.721885   
3                         0.241711                     0.010123   
4                         0.551796                     0.001268   
..                             ...                          ...   
473 

### PCA

In [110]:
def is_related(pair1, pair2):
    if (pair1[0] in pair2 or pair1[1] in pair2) and pair1!=pair2 and not (pair1[0]==pair2[1] and pair1[1]==pair2[0]):
        return True
    return False

def add_relation(corr_fea):
    for i in range(len(corr_fea)):
        for j in range(i,len(corr_fea)):
            if i!=j:
                if is_related(corr_fea[i],corr_fea[j]):
                    fea1=tuple(set(corr_fea[i])-set(corr_fea[j]))
                    fea2=tuple(set(corr_fea[j])-set(corr_fea[i]))
                    fea=fea1+fea2
                    if fea not in corr_fea and rev(fea) not in corr_fea:
                        corr_fea.append((fea1+fea2))

def rev(fea):
    f1=fea[0]
    f2=fea[1]

    return (f2,f1)

corr=X_train.corr()
corr=corr.where(abs(corr)>0.9)
count=0
corr_fea=[]
for i in corr.columns:
    for j in corr.columns:
        if i!=j and abs(corr[i][j])>0.9 and ((i,j) not in corr_fea) and ((j,i) not in corr_fea):
            count+=1
            corr_fea.append((i,j))
            add_relation(corr_fea)


In [111]:
from sklearn.decomposition import PCA

new_num_fea=len(X_train.columns)-count

pca=PCA(n_components=new_num_fea)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)


### Feature Selection

In [112]:
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC

selector=RFECV(SVC(kernel="linear"),step=2000,min_features_to_select=10)
X_train=selector.fit_transform(X_train,y_train)
X_test=selector.transform(X_test)
X_train

# from sklearn.feature_selection import S

array([[-4.35381412e-01,  1.09358880e-01,  5.88588002e-01, ...,
        -7.63587318e-03, -7.10771208e-03, -2.95793265e-02],
       [-1.03724378e+00,  3.23960533e-01,  1.26919693e+00, ...,
         2.50070012e-02, -2.55934937e-02, -5.69553311e-02],
       [-2.47742268e+00,  1.51527950e+00, -4.22775172e-01, ...,
        -9.11002724e-02, -4.96205702e-02,  2.78973442e-02],
       ...,
       [ 2.29170429e+00, -3.77099481e-01,  7.19067268e-01, ...,
         1.34276178e-02, -3.50646136e-02, -1.99981715e-02],
       [-9.08768481e-01, -1.21430527e+00,  1.22266588e+00, ...,
         2.96633966e-02, -1.38802275e-02,  4.16677115e-02],
       [ 1.00276930e+00, -1.73693065e+00, -7.03053680e-01, ...,
        -4.22872383e-02, -5.45876039e-03,  1.94340175e-03]])

In [113]:

# c=dataset.corr().abs()
# s=c.unstack()
# so=s.sort_values(kind="quicksort")





# delcol=[]
# c=dataset.corr().shape[0]

# names=dataset.corr().columns
#
# for i in range(c):
#     for j in range(i+1,c):
#         if dataset.corr().iloc[i,j]>0.8 :
#             delcol.append((names[i],names[j]))
# print(len(delcol))
#
# import numpy as np
# np.a
#
# for i in range(c):
#     count = 0
#     for j in range(c):
#         if dataset.corr().iloc[i,j]>0.8:
#             count += 1





# Methods

In [114]:
from sklearn.metrics import confusion_matrix
from sklearn.tree import  DecisionTreeClassifier
from sklearn.metrics import classification_report
clf=DecisionTreeClassifier(max_features=4,max_depth=5,class_weight='balanced')
clf.fit(X_train,y_train)
# clf.predict(X_test)

print(classification_report(y_test,clf.predict(X_test)))
# print(classification_report(y_train,clf.predict(X_train)))
confusion_matrix(y_test,clf.predict(X_test))

              precision    recall  f1-score   support

           0       0.76      0.42      0.54        60
           1       0.24      0.58      0.34        19

    accuracy                           0.46        79
   macro avg       0.50      0.50      0.44        79
weighted avg       0.63      0.46      0.49        79



array([[25, 35],
       [ 8, 11]], dtype=int64)

In [115]:



from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(hidden_layer_sizes=(12,40),activation="relu",max_iter=200,batch_size=20)
# cross_val_score(clf,X_train,y_train,cv=3)


clf.fit(X_train,y_train)
print(classification_report(y_test,clf.predict(X_test)))
confusion_matrix(y_test,clf.predict(X_test))
confusion_matrix(y_train,clf.predict(X_train))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87        60
           1       0.60      0.47      0.53        19

    accuracy                           0.80        79
   macro avg       0.72      0.69      0.70        79
weighted avg       0.79      0.80      0.79        79



array([[239,   0],
       [  0, 239]], dtype=int64)

In [116]:
from sklearn.ensemble import RandomForestClassifier

forest=RandomForestClassifier(class_weight="balanced")
forest.fit(X_train,y_train)
confusion_matrix(forest.predict(X_test),y_test)

array([[55, 17],
       [ 5,  2]], dtype=int64)

In [117]:
# from sklearn.metrics import classification_report, confusion_matrix
# from sklearn.neural_network import MLPClassifier
# clf=MLPClassifier(hidden_layer_sizes=(12,40,23,30),activation="relu",max_iter=500,batch_size=20)
# # cross_val_score(clf,X_train,y_train,cv=3)
# from sklearn.feature_selection import SequentialFeatureSelector
# sfs=SequentialFeatureSelector(clf,n_features_to_select="auto")
#
# sfs.fit(X_train,y_train)
# print(classification_report(y_test,sfs.predict(X_test)))
# confusion_matrix(y_test,sfs.predict(X_test))
# confusion_matrix(y_train,sfs.predict(X_train))